// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0VhKXUgP34sKZhvAezX8iZPQ50Btk-c',
    appId: '1:770271142098:web:a71a0fab52b69a32300d0b',
    messagingSenderId: '770271142098',
    projectId: 'maps-codexveer',
    authDomain: 'maps-codexveer.firebaseapp.com',
    storageBucket: 'maps-codexveer.appspot.com',
    measurementId: 'G-ZC4Q5DVHVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfsnAhPwM5hqaU-oadT6zmI-9TgcmsTs8',
    appId: '1:770271142098:android:76a3419afd976c93300d0b',
    messagingSenderId: '770271142098',
    projectId: 'maps-codexveer',
    storageBucket: 'maps-codexveer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPIU_zZ_85pKlAMnKE4GpMkvYlV2Yg6nI',
    appId: '1:770271142098:ios:55020f56aa47e1d0300d0b',
    messagingSenderId: '770271142098',
    projectId: 'maps-codexveer',
    storageBucket: 'maps-codexveer.appspot.com',
    iosClientId:
        '770271142098-6riugr6bql1itcqm4epl8tdg6c9rqkbe.apps.googleusercontent.com',
    iosBundleId: 'com.codexveer.googleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPIU_zZ_85pKlAMnKE4GpMkvYlV2Yg6nI',
    appId: '1:770271142098:ios:55020f56aa47e1d0300d0b',
    messagingSenderId: '770271142098',
    projectId: 'maps-codexveer',
    storageBucket: 'maps-codexveer.appspot.com',
    iosClientId:
        '770271142098-6riugr6bql1itcqm4epl8tdg6c9rqkbe.apps.googleusercontent.com',
    iosBundleId: 'com.codexveer.googleMaps',
  );
}
